name: Workflow from CLI

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  URL: ${{ vars.REGISTRY_URL }}
  IMAGE: ${{ vars.IMAGE }}
  HASH: ${{ github.sha }}

jobs:
  general:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Docker Build
        run: |
          docker build \
            -t $IMAGE:latest \
            -t $IMAGE:$HASH .

      - name: Running
        run: |
          echo "Running from CLI"
          dotnet --version
          echo "CLI Variable: ${{ vars.BOOTS }}"

      - name: Variables
        run: echo "$HASH, ${{ github.repository }}, $URL"

      - name: Hook
        run: |
          curl -X POST ${{ vars.HOOK_URL }} \
            -H "Authorization: Bearer ${{ secrets.HOOK_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"image": "${{ env.IMAGE }}:${{ env.HASH }}"}';

        #      - name: Docker Login
        #        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} ${{ vars.REGISTRY_URL }} --password-stdin
